### ISSUE TITLE
[bug]iOS端，Chrome浏览器，热力图左侧年份会被截断展示

### ISSUE THREAD

**Issue by erispyu** [codepzj/hexo-graph#3]
**Device**: iPhone 15 Pro Max
**OS**: iOS 18.1.1 (22B91)
**Web Browser**: Google Chrome 131.0.6778.154
![image](https://github.com/user-attachments/assets/852fb4a7-b88b-45b7-be26-256d590827ab)

**Comment by codepzj** [comment]
已修复

**Comment by erispyu** [comment]
> 已修复

感谢修复，新年快乐！
